#---------------------------------#
#      general configuration      #
#---------------------------------#

branches:
  only:
    - master

install:
  - choco install gitversion.portable -y
  - ps: gitversion /l console /output buildserver
  - ps: Update-AppveyorBuild -Version $GitVersion_FullSemVer

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: $(GitVersion_AssemblySemVer)
  assembly_file_version: $(GitVersion_MajorMinorPatch).$(APPVEYOR_BUILD_NUMBER)
  assembly_informational_version: $(GitVersion_InformationalVersion)
  
#---------------------------------#
#    environment configuration    #
#---------------------------------#

image:
- Visual Studio 2017

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform:
  - Any CPU

configuration:
  - Release

build:
  project: Source\SharpVectors.sln

after_build:
  - ps: nuget pack "Source\SharpVectorsReloaded.nuspec" -Properties "version=$env:GitVersion_NuGetVersionV2"

#---------------------------------#
#      packaging artifacts        #
#---------------------------------#

artifacts:
  - path: '**\*.nupkg'

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy:
  - provider: NuGet
    api_key:
      secure: <your secret here>
    skip_symbols: true
    artifact: /.*\.nupkg/
    on:
      APPVEYOR_REPO_TAG: true
